mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView


urlpatterns = [
    path('noon/', include('noon.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', RedirectView.as_view(url='noon/', permanent=True))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

mysite/noon/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('all_restaurants/', views.all_restaurants, name='all_restaurants'),
    path('search/', views.search, name='search'),
    path('profile/', views.profile, name='profile'),
    path('administration/<int:pk>', views.RestaurantWeeklyMenuUpdateView.as_view(), name='administration_form'),
    path('administration/', views.RestaurantByUserListView.as_view(), name='administration'),
    path('user_login/', views.user_login, name='user_login'),
    path('register/', views.register, name='register'),
    path('location/<slug:some_slug>', views.location, name='location'),
]

mysite/noon/models.py
from django.db import models
from django.db.models import ForeignKey
from django.urls import reverse
import datetime
from django.contrib.auth.models import User
from datetime import date
from django.forms import ModelForm

class Location(models.Model):
    location = models.CharField('Name of the Area', max_length=200, help_text='Input names of the areas in the city')

    def display_restaurants(self):
        return ', '.join(location.name for location in self.locations.all()[:3])

    display_restaurants.short_description = 'Restaurants'

    def __str__(self):
        return self.location

class Restaurant(models.Model):
    name = models.CharField('Name', max_length=200)
    restaurant_location = models.ForeignKey('Location', help_text="Choose restaurant's location", on_delete=models.CASCADE, null=True, related_name='locations')
    address = models.CharField('Street address', max_length=200, null=True)
    lunch_hours = models.CharField('Lunch hours', max_length=200, help_text='Lunch serving hours', default="11am - 3pm")
    favourites = models.ManyToManyField(User, related_name='favourites', blank=True)

    def __str__(self):
        return f"{self.name}: {self.restaurant_location}, {self.address}, {self.lunch_hours}"

class RestaurantWeeklyMenu(models.Model):
    restaurant = models.ForeignKey(Restaurant, verbose_name='Restaurant', on_delete=models.SET_NULL, null=True, related_name='restaurant')
    soup = models.CharField('Soup', max_length=200, blank=True, null=True)
    first_main = models.CharField('First Main', max_length=200, blank=True, default = 'main')
    second_main = models.CharField('Second Main', max_length=200, blank=True, null=True)
    third_main = models.CharField('Third Main', max_length=200, blank=True, null=True)
    dessert = models.CharField('Dessert', max_length=200, blank=True, null=True)
    visitor = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    WEEK_DAYS = (
        ('1', 'Monday'),
        ('2', 'Tuesday'),
        ('3', 'Wednesday'),
        ('4', 'Thursday'),
        ('5', 'Friday'),
    )

    weekday = models.CharField(
        max_length=1,
        choices=WEEK_DAYS,
        blank=True,
        default='1',
        help_text='Weekday',
            )

    def __str__(self):
        return f'{self.restaurant}: {self.weekday}'

mysite/noon/forms.py
from django.forms import ModelForm

from .models import RestaurantWeeklyMenu
from django import forms
from django.contrib.auth.models import User

class RestaurantWeeklyMenuForm(forms.ModelForm):
    class Meta:
        model = RestaurantWeeklyMenu
        fields = ['soup', 'first_main', 'second_main', 'third_main', 'dessert']
        widgets = {'restaurant': forms.HiddenInput(), 'visitor': forms.HiddenInput(), 'weekday': forms.HiddenInput()}

mysite/noon/views.py
from datetime import datetime

from django.contrib import auth
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User, Group
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect, request
from django.urls import reverse
from django.views import generic
from .forms import RestaurantWeeklyMenuForm

from .models import Location, Restaurant, RestaurantWeeklyMenu
from django.core.paginator import Paginator
from django.db.models import Q
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.shortcuts import render
from .forms import RestaurantWeeklyMenuForm
from django.views.generic.edit import FormMixin, UpdateView
from django.views.decorators.csrf import csrf_protect
from django.contrib import messages


def index(request):
    today = datetime.today().isoweekday()
    restaurants = RestaurantWeeklyMenu.objects.filter(weekday__exact=today)
    day_menus_num = RestaurantWeeklyMenu.objects.filter(weekday__exact=today).count()
    num_iter = list(range(1, day_menus_num + 1))
    grouped_list = zip(num_iter, restaurants)
    context = {
        'grouped_list': grouped_list,       'num_iter': num_iter,
    }
    return render(request, 'index.html', context=context)

def all_restaurants(request):
    num_restaurants = Restaurant.objects.all().count()
    num_iter = list(range(1, num_restaurants+1))
    restaurants = Restaurant.objects.all()
    paginator = Paginator(restaurants, 8)
    page_number = request.GET.get('page')
    restaurants = paginator.get_page(page_number)

    paginator2 = Paginator(num_iter, 8)
    page_number2 = request.GET.get('page')
    num_iter = paginator2.get_page(page_number2)

    today = datetime.today().isoweekday()
    day_menus = RestaurantWeeklyMenu.objects.filter(weekday__exact=today)
    paginator3 = Paginator(day_menus, 8)
    page_number3 = request.GET.get('page')
    day_menus = paginator3.get_page(page_number3)
    grouped_list = zip(num_iter, restaurants, day_menus)

    context = {
        'grouped_list': grouped_list,
        'num_iter': num_iter,
    }
    return render(request, 'all_restaurants.html', context=context)

def search(request):
    query = request.GET.get('q')
    today = datetime.today().isoweekday()

    search_results_restaurants = RestaurantWeeklyMenu.objects.filter(Q(restaurant__name__icontains=query) & Q(weekday=today))
    search_results_dish = RestaurantWeeklyMenu.objects.filter((Q(soup__icontains=query) | Q(first_main__icontains=query) | Q(second_main__icontains=query) | Q(third_main__icontains=query) | Q(dessert__icontains=query)) & Q(weekday=today))

    num_restaurants = len(search_results_dish)
    num_iter = list(range(1, (num_restaurants + 1)))
    grouped_list = zip(num_iter, search_results_dish)

    num_restaurants2 = len(search_results_restaurants)
    num_iter2 = list(range(1, (num_restaurants2 + 1)))
    grouped_list2 = zip(num_iter2, search_results_restaurants)

    context = {
        'num_iter': num_iter,
        'grouped_list': grouped_list,
        'num_iter2': num_iter2,
        'grouped_list2': grouped_list2
    }

    return render(request, 'search.html', context=context)


def favourites(request):
    query = request.GET.get()
    restaurant = get_object_or_404(Restaurant, pk=restaurant_id)
    if restaurant.favourites.filter(id=request.user.ide).exist():
        restaurant.favourites.remove(request.user)
    else:
        restaurant.favourites.add(request.user)

    return render(request, 'profile.html')


@login_required
def profile(request):
    user = request.user
    today = datetime.today().isoweekday()
    number = user.favourites.all().count()
    num_iter = list(range(1, number + 1))
    favourite_restaurants = user.favourites.all()
    menus = RestaurantWeeklyMenu.objects.filter(id=request.user.id)
    grouped_list = zip(num_iter, favourite_restaurants, menus)
    context = {
        'num_iter': num_iter,
        'grouped_list': grouped_list}

    return render(request, 'profile.html', context=context)

def location(request, some_slug):

    restaurants = Restaurant.objects.filter(restaurant_location__location=some_slug)
    menus = RestaurantWeeklyMenu.objects.filter(restaurant__restaurant_location__location=some_slug)
    num_restaurants = len(restaurants)
    num_iter = list(range(1, (num_restaurants + 1)))
    grouped_list = zip(num_iter, restaurants, menus)
    context = {
        'some_slug': some_slug,
        'num_iter': num_iter,
        'grouped_list': grouped_list
    }
    return render(request, 'location.html', context=context)

class RestaurantByUserListView(LoginRequiredMixin, generic.ListView):
    model = RestaurantWeeklyMenu
    template_name = 'administration.html'
    context_object_name = 'menus'

    def get_queryset(self):
        return RestaurantWeeklyMenu.objects.filter(visitor=self.request.user)


class RestaurantWeeklyMenuUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = RestaurantWeeklyMenu
    fields = ['soup', 'first_main', 'second_main', 'third_main', 'dessert']
    success_url = "administration"
    template_name = 'administration_form.html'

    def form_valid(self, form):
        form.instance.visitor = self.request.user
        return super().form_valid(form)

    def test_func(self):
        restaurant = self.get_object()
        return self.request.user == restaurant.visitor


@login_required
def user_login(request):
    if request.user.groups.filter(name='restaurants').exists():
        return redirect('/noon/administration')
    elif request.user.groups.filter(name='visitors').exists():
        return redirect('/noon/profile')
    else:
        return render(request, 'login.html', )


@csrf_protect
def register(request):
    if request.method == "POST":
        username = request.POST['username']
        email = request.POST['email']
        password = request.POST['password']
        password2 = request.POST['password2']
        if password == password2:
            if User.objects.filter(username=username).exists():
                messages.error(request, f'Username {username} is taken!')
                return redirect('register')
            else:
                if User.objects.filter(email=email).exists():
                    messages.error(request, f'User with this email {email} already exists!')
                    return redirect('register')
                else:
                    group = Group.objects.get(name='visitors')
                    User.objects.create_user(username=username, email=email, password=password).groups.add(group)
                messages.error(request, 'Passwords do not match!')
            return redirect('register')
    return render(request, 'register.html')

mysite/noon/templates/administration.html
{% extends "base.html" %}
{% block title %}<title>Administration</title>{% endblock %}
{% block content %}
 <div class="weekly_menu">
    <h1>Your weekly menu:</h1>
    {% if menus %}
    <ul>
       {% for menu in menus %}
        <li >
        <h4>Day: {{menu.get_weekday_display}}</h4>
      </li>
      <li >
        <p>Soup:{{menu.soup}}</p>
      </li>
      <li >
        <p>First main:{{menu.first_main}}</p>
      </li>
      <li >
        <p>Second main:{{menu.second_main}}</p>
      </li>
      <li >
        <p>Third main:{{menu.third_main}}</p>
      </li>
       <li >
        <p>Dessert:{{menu.dessert}}</p>
      </li>
        <a href="{% url 'administration_form' menu.id %}"><button class="update">Update</button></a>
      {% endfor %}
    </ul>
    {% else %}
      <p>No menu update available</p>
    {% endif %}

</div>
{% endblock %}

mysite/noon/templates/administration_form.html
{% extends "base.html" %}
{% block title %}<title>Administration</title>{% endblock %}
{% block content %}
    {% if object.visitor == user %}
    <h2>Update menu</h2>
      <div class="fieldWrapper" style="height: 425px;">
        <hr><br/>
        <form action="#" method="post">
          {% csrf_token %}
          {{ form }}</br>
          <input type="submit" value="Save">
        </form>
      </div>
      {% endif %}
{% endblock %}

mysite/noon/templates/all_restaurants.html
{% extends "base.html" %}
{% block title %}<title>All Restaurants</title>{% endblock %}

{% block content %}
     <div class="row two_rows" >
            {% for item1, item2, item3 in grouped_list %}
                <div class="tab {{ item1 }}">
                    <h4>{{ item3.restaurant.name }}</h4>
                    <p>{% if item3.soup %}{{ item3.soup }}{% else %} &nbsp; {% endif %}</p>
                    <p>{% if item3.first_main %}{{ item3.first_main }}{% else %} &nbsp; {% endif %}</p>
                    <p>{% if item3.second_main %}{{ item3.second_main }}{% else %} &nbsp; {% endif %}</p>
                    <p>{% if item3.third_main %}{{ item3.third_main }}{% else %} &nbsp; {% endif %}</p>
                    <p>{% if item3.dessert %}{{ item3.dessert }}{% else %} &nbsp; {% endif %}</p>
                </div>
            {% endfor %}
    </div>
    {% for a in num_iter %}
    {% endfor %}
    <div class="pagination" >
          {% if num_iter.has_other_pages %}
            {% for i in num_iter.paginator.page_range %}
               {% if users.number == i %}
                    <span class="current" style="text-decoration:none; color:white">{{ i }} </span>
               {% else %}
                    <a href="?page={{ i }}">{{ i }}</a>
               {% endif %}
            {% endfor %}
          {% endif %}
      </div>
{% endblock %}



<!--<div class="center" >-->
<!--            <ul class="pagination" syle="display:inline;">-->
<!--                {% if num_iter.has_previous %}-->
<!--                  <li ><a href="?page={{ num_iter.previous_page_number }}">&laquo;</a></li>-->
<!--                {% else %}-->
<!--                  <li class="disabled"><span>&laquo;</span></li>-->
<!--                {% endif %}-->
<!--                {% for i in num_iter.paginator.page_range %}-->
<!--                  {% if users.number == i %}-->
<!--                    <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>-->
<!--                  {% else %}-->
<!--                    <li><a href="?page={{ i }}">{{ i }}</a></li>-->
<!--                  {% endif %}-->
<!--                {% endfor %}-->
<!--                {% if num_iter.has_next %}-->
<!--                  <li><a href="?page={{ num_iter.next_page_number }}">&raquo;</a></li>-->
<!--                {% else %}-->
<!--                  <li class="disabled"><span>&raquo;</span></li>-->
<!--                {% endif %}-->
<!--            </ul>-->
<!--         </div>-->

mysite/noon/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% block title %}<title>Noon</title>{% endblock %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,100;0,300;0,400;0,700;1,300&family=Roboto:ital,wght@0,100;0,300;0,400;0,900;1,100&display=swap"
        rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://unpkg.com/swiper@8/swiper-bundle.min.css" />
    <script src="https://unpkg.com/swiper@8/swiper-bundle.min.js"></script>
    <script src="https://kit.fontawesome.com/932e7aff45.js" crossorigin="anonymous"></script>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    <nav class="top_menu">
        <div class="language">
            <button class="english">EN</button>
            <button class="lithuanian" >LT</button>
        </div>
        <a href="/"><img src="/static/img/logo.png" height="70" width="220"/></a>
        {% if user.is_authenticated %}
            <div class="loggedin">
                <a href="{% url 'user_login'%}?next=/noon" style="text-decoration: underline; color: black";><p>{{ user.get_username }}</p></a>
                <a href="{% url 'logout'%}?next=/noon"><button class="login">Log out</button></a>
            </div>
            {% else %}
            <div class="signbuttons">
                <a href="{% url 'login'%}"><button class="login">Log in</button></a>
                <a href="{% url 'register'%}"><button class="signup">Sign Up</button></a>
            </div>
        {% endif %}
    </nav>
    {% block content %}

    {% endblock %}
    <div class="footer">
        <a href="{% url 'login'%}">For restaurants</a>
    </div>
    {% block extrascripts %}{% endblock %}
</body>
</html>
{# some text #}
{% comment 'coment example' %}
{% endcomment %}

mysite/noon/templates/index.html
{% extends "base.html" %}
{% block title %}<title>NOON</title>{% endblock %}
{% load static %}
{% block content %}
    <div class="top_greeting">
        <h2>Today's lunch offers</h2>
        <div class="search">
            <form action="{% url 'search' %}"  method="get" class="form-inline my-2 my-md-0">
            <input name="q" class="form-control" placeholder="&#xf002; Search" style="font-family:Arial, FontAwesome">
        </div>
    </div>
    <div class="swiper">
        <div class="row">
            {% for item1, item2 in grouped_list %}
                <div class="tab {{ item1 }}">
                    <h4>{{ item2.restaurant.name }}</h4>
                    <p>{% if item2.soup %}{{ item2.soup }}{% else %} &nbsp; {% endif %}</p>
                    <p>{% if item2.first_main %}{{ item2.first_main }}{% else %} &nbsp; {% endif %}</p>
                    <p>{% if item2.second_main %}{{ item2.second_main }}{% else %} &nbsp; {% endif %}</p>
                    <p>{% if item2.third_main %}{{ item2.third_main }}{% else %} &nbsp; {% endif %}</p>
                    <p>{% if item2.dessert %}{{ item2.dessert }}{% else %} &nbsp; {% endif %}</p>
                </div>
            {% endfor %}
        </div>
        <div class="swiper-button-prev"></div>
        <div class="swiper-button-next"></div>
    </div>
    <div class="map_section">
        <img src="/static/img/map.png" alt="Vilnius" usemap="#vilniusmap" height="400">
            <map name="vilniusmap">
                <area shape="circle" coords="460, 317, 40" alt="uzupis_paupys" href="{% url 'location' some_slug='Uzupis' %}"  style="cursor:pointer">
                <area shape="circle" coords="345, 303, 40" alt="senamiestis" href="{% url 'location' some_slug='Senamiestis' %}" style="cursor:pointer">
                <area shape="circle" coords="245, 291, 40" alt="naujamiestis" href="{% url 'location' some_slug='Naujamiestis' %}" style="cursor:pointer">
                <area shape="circle" coords="290, 118, 40" alt="snipiskes" href="{% url 'location' some_slug='Snipiskes' %}" style="cursor:pointer">
                <area shape="circle" coords="400, 88, 40" alt="zirmunai" href="{% url 'location' some_slug='Zirmunai' %}" style="cursor:pointer">
                <area shape="circle" coords="500, 154, 40" alt="antakalnis" href="{% url 'location' some_slug='Antakalnis' %}" style="cursor:pointer">
            </map>
        <div class="map_text">
            <h3> Press on the area to find lunch offers near you</h3>
            <a class="view_all" href="{% url 'all_restaurants' %}">View All</a>
        </div>
    </div>
{% block extrascripts %}<script src="{% static 'js/script.js' %}"></script>{% endblock %}
{% endblock %}

mysite/noon/templates/location.html
{% extends "base.html" %}

{% block title %}<title>Location</title>{% endblock %}

{% block content %}
    <h2>Day lunch offers in {{ some_slug }}:</h2>
    <div class="row two_rows" >
      <div class="row" style="height: 425px;">
            {% for item1, item2, item3 in grouped_list %}
                <div class="tab {{ item1 }}">
                    <h4>{{ item2.name }}</h4>
                    <p>{% if item3.soup %}{{ item3.soup }}{% else %} &nbsp; {% endif %}</p>
                    <p>{% if item3.first_main %}{{ item3.first_main }}{% else %} &nbsp; {% endif %}</p>
                    <p>{% if item3.second_main %}{{ item3.second_main }}{% else %} &nbsp; {% endif %}</p>
                    <p>{% if item3.third_main %}{{ item3.third_main }}{% else %} &nbsp; {% endif %}</p>
                    <p>{% if item3.dessert %}{{ item3.dessert }}{% else %} &nbsp; {% endif %}</p>
                </div>
            {% endfor %}
       </div>
    </div>
{% endblock %}

mysite/noon/templates/profile.html
{% extends "base.html" %}

{% block title %}<title>Personal</title>{% endblock %}

{% block content %}
   <h2>Your favourite restaurants' menus today: </h2>
        <div class="row two_rows" >
        {% for item1, item2, item3  in grouped_list %}
                <div class="tab {{ item1 }}">
                    <h4>{{ item2.name }}</h4>
                    <p>{% if item3.soup %}{{ item3.soup }}{% else %} &nbsp; {% endif %}</p>
                    <p>{% if item3.first_main %}{{ item3.first_main }}{% else %} &nbsp; {% endif %}</p>
                    <p>{% if item3.second_main %}{{ item3.second_main }}{% else %} &nbsp; {% endif %}</p>
                    <p>{% if item3.third_main %}{{ item3.third_main }}{% else %} &nbsp; {% endif %}</p>
                    <p>{% if item3.dessert %}{{ item3.dessert }}{% else %} &nbsp; {% endif %}</p>

                </div>
        {% endfor %}
        </div>

{% endblock %}

mysite/noon/templates/register.html
{% extends "base.html" %}
{% block title %}<title>Sign up</title>{% endblock %}
{% block content %}
   {% if messages %}
            {% for message in messages %}
                <div class="alert alert-danger" role="alert">
                    {{ message }}
                </div>
            {% endfor %}
    {% endif %}
    <div class="container register">
        <h3>Registration</h3><br/>
        <form method="post" action="{% url 'login' %}">
            {% csrf_token %}
            <div class="form-group">
                <label for="username">User name</label>
                <input name="username" type="text" class="form-control" id="username" aria-describedby="usernameHelp">

            </div>
            <div class="form-group">
                <label for="exampleInputEmail1">Email</label>
                <input name="email" type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">

            </div>
            <div class="form-group">
                <label for="password">Password</label>
                <input name="password" type="password" class="form-control" id="password" aria-describedby="pwdHelp">
                <small id="pwdHelp" class="form-text text-muted">* or more caharacters. Must include letters and digits</small>
            </div>
            <div class="form-group">
                <label for="password2">Repeat</label>
                <input name="password2" type="password" class="form-control" id="password2" aria-describedby="pwd2Help">
            </div>
            <button type="submit" class="btn btn-primary register-button">Submit</button>
        </form>
        <p>You already have and account with us<a href="/login"> Log in</a></p>
    </div>

{% endblock %}

mysite/noon/templates/search.html
{% extends "base.html" %}
{% block title %}<title>Search results</title>{% endblock %}
{% block content %}
    {% if num_iter %}
        <h2>Search results:</h2>
        <div class="row" style="height: 425px;">
            {% for item1, item2 in grouped_list %}
                <div class="tab {{ item1 }}">
                    <h4>{{ item2.restaurant.name }}</h4>
                    <p>{% if item2.soup %}{{ item2.soup }}{% else %} &nbsp; {% endif %}</p>
                    <p>{% if item2.first_main %}{{ item2.first_main }}{% else %} &nbsp; {% endif %}</p>
                    <p>{% if item2.second_main %}{{ item2.second_main }}{% else %} &nbsp; {% endif %}</p>
                    <p>{% if item2.third_main %}{{ item2.third_main }}{% else %} &nbsp; {% endif %}</p>
                    <p>{% if item2.dessert %}{{ item2.dessert }}{% else %} &nbsp; {% endif %}</p>
                </div>
        </div>
            {% endfor %}
    {% elif num_iter2 %}
        <div class="row" style="height: 425px;">
            {% for item1, item2 in grouped_list2 %}
                <div class="tab {{ item1 }}">
                    <h4>{{ item2.restaurant.name }}</h4>
                    <p>{% if item2.soup %}{{ item2.soup }}{% else %} &nbsp; {% endif %}</p>
                    <p>{% if item2.first_main %}{{ item2.first_main }}{% else %} &nbsp; {% endif %}</p>
                    <p>{% if item2.second_main %}{{ item2.second_main }}{% else %} &nbsp; {% endif %}</p>
                    <p>{% if item2.third_main %}{{ item2.third_main }}{% else %} &nbsp; {% endif %}</p>
                    <p>{% if item2.dessert %}{{ item2.dessert }}{% else %} &nbsp; {% endif %}</p>
                </div>
        </div>
            {% endfor %}
    {% else %}
        <p style="margin-bottom: 400">No results</p>
    {% endif %}

{% endblock %}